#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "MANIFEST.json"
EXCLUDED_NAMES = {"MANIFEST.json"}
EXCLUDED_PARTS = {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}
RUNTIME_DIR_NAMES = {".cpt-eval-runs", ".cpt-eval-live"}
ROOT_LOCAL_NAMES = {"AGENTS.md"}
ROOT_LOCAL_DIRS = {".cpt", ".runtime"}


def canonical_bytes(path: Path) -> bytes:
    data = path.read_bytes()
    if b"\0" in data:
        return data
    return data.replace(b"\r\n", b"\n")


def sha256(path: Path) -> str:
    return hashlib.sha256(canonical_bytes(path)).hexdigest()


def excluded(rel: Path) -> bool:
    if rel.name in EXCLUDED_NAMES:
        return True
    if len(rel.parts) == 1 and rel.name in ROOT_LOCAL_NAMES:
        return True
    if rel.parts and rel.parts[0] in ROOT_LOCAL_DIRS:
        return True
    if any(part in EXCLUDED_PARTS or part in RUNTIME_DIR_NAMES for part in rel.parts):
        return True
    if rel.suffix in EXCLUDED_SUFFIXES:
        return True
    # Evaluation reports are generated by local/CI runs. Only the empty marker
    # is packaged so the directory exists in source checkouts.
    if len(rel.parts) >= 3 and rel.parts[:3] == ("evaluation", "executable", "reports"):
        return rel.name != ".gitkeep"
    if rel.name.endswith("-comparison.json"):
        return True
    return False


def included_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if not excluded(rel):
            files.append(path)
    return sorted(files, key=lambda item: item.relative_to(ROOT).as_posix())


def main() -> int:
    files = included_files()
    data = {
        "schema": "cpt-package-manifest-v10",
        "name": "codex-product-os",
        "version": "4.1.0",
        "phase": "offline-certified-live-pending",
        "release_lineage": [
            "4.0.0",
            "4.1.0",
        ],
        "custom_patches": [],
        "manifest_excludes": [
            "MANIFEST.json",
            "**/__pycache__/**",
            "**/*.pyc",
            "**/*.pyo",
            "**/.pytest_cache/**",
            "**/.mypy_cache/**",
            "**/.ruff_cache/**",
            "**/.cpt-eval-runs/**",
            "**/.cpt-eval-live/**",
            "/.cpt/**",
            "/.runtime/**",
            "/AGENTS.md",
            "evaluation/executable/reports/** except .gitkeep",
            "**/*-comparison.json",
        ],
        "file_count": len(files),
        "inventories": {
            "plugins": 6,
            "canonical_skills": 49,
            "legacy_skill_mappings": 95,
            "design_intelligence_dimensions": 16,
            "design_intelligence_cases": 20,
            "interaction_behavior_lenses": 12,
            "interaction_patterns": 44,
            "form_flow_modes": 8,
            "form_patterns": 24,
            "professional_workflow_classes": 7,
            "design_execution_adapters": 2,
            "logical_roles": 50,
            "quality_gates": 25,
            "routing_profiles": 14,
            "knowledge_artifact_types": 6,
            "knowledge_templates": 6,
            "knowledge_examples": 3,
            "knowledge_lifecycle_cases": 11,
            "enforcement_policy_cases": 5,
            "enforcement_integration_checks": 13,
            "worker_archetypes": 10,
            "orchestration_policy_cases": 34,
            "orchestration_integration_checks": 16,
            "behavior_tests": 136,
            "installation_receipt_tests": 5,
            "manager_registry_tests": 5,
            "manager_planning_tests": 10,
            "executable_evaluation_cases": 21,
            "fixture_repositories": 6,
            "evaluation_suites": 4,
            "evaluation_unit_tests": 13,
            "migration_tests": 7,
            "release_unit_tests": 10,
            "release_tracks": 33,
            "release_gates": 9,
            "mutation_cases": 4,
            "hooks": 9,
            "rules_profiles": 2,
            "ci_workflows": 2,
        },
        "files": [
            {
                "path": path.relative_to(ROOT).as_posix(),
                "size": len(canonical_bytes(path)),
                "sha256": sha256(path),
            }
            for path in files
        ],
    }
    MANIFEST.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"MANIFEST BUILT: {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
