#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "MANIFEST.json"
EXCLUDED_NAMES = {"MANIFEST.json"}
EXCLUDED_PARTS = {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}
RUNTIME_DIR_NAMES = {".cpt-eval-runs", ".cpt-eval-live"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def excluded(rel: Path) -> bool:
    if rel.name in EXCLUDED_NAMES:
        return True
    if any(part in EXCLUDED_PARTS or part in RUNTIME_DIR_NAMES for part in rel.parts):
        return True
    if rel.suffix in EXCLUDED_SUFFIXES:
        return True
    # Evaluation reports are generated by local/CI runs. Only the empty marker
    # is packaged so the directory exists in source checkouts.
    if len(rel.parts) >= 3 and rel.parts[:3] == ("evaluation", "executable", "reports"):
        return rel.name != ".gitkeep"
    if rel.name.endswith("-comparison.json"):
        return True
    return False


def included_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if not excluded(rel):
            files.append(path)
    return sorted(files, key=lambda item: item.relative_to(ROOT).as_posix())


def main() -> int:
    files = included_files()
    data = {
        "schema": "cpt-package-manifest-v9",
        "name": "codex-product-os",
        "version": "4.0.0-beta.1",
        "phase": "rc-trials-offline-beta",
        "manifest_excludes": [
            "MANIFEST.json",
            "**/__pycache__/**",
            "**/*.pyc",
            "**/*.pyo",
            "**/.pytest_cache/**",
            "**/.mypy_cache/**",
            "**/.ruff_cache/**",
            "**/.cpt-eval-runs/**",
            "**/.cpt-eval-live/**",
            "evaluation/executable/reports/** except .gitkeep",
            "**/*-comparison.json",
        ],
        "file_count": len(files),
        "inventories": {
            "plugins": 6,
            "canonical_skills": 45,
            "legacy_skill_mappings": 95,
            "logical_roles": 50,
            "quality_gates": 25,
            "routing_profiles": 14,
            "knowledge_artifact_types": 6,
            "knowledge_templates": 6,
            "knowledge_examples": 3,
            "knowledge_lifecycle_cases": 11,
            "enforcement_policy_cases": 5,
            "enforcement_integration_checks": 13,
            "worker_archetypes": 10,
            "orchestration_policy_cases": 34,
            "orchestration_integration_checks": 16,
            "behavior_tests": 115,
            "executable_evaluation_cases": 21,
            "fixture_repositories": 6,
            "evaluation_suites": 4,
            "evaluation_unit_tests": 13,
            "migration_tests": 7,
            "release_unit_tests": 10,
            "release_tracks": 33,
            "release_gates": 9,
            "mutation_cases": 4,
            "hooks": 9,
            "rules_profiles": 2,
            "ci_workflows": 2,
        },
        "files": [
            {
                "path": path.relative_to(ROOT).as_posix(),
                "size": path.stat().st_size,
                "sha256": sha256(path),
            }
            for path in files
        ],
    }
    MANIFEST.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"MANIFEST BUILT: {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
